blank_issues_enabled: true
contact_links:
  - name: ğŸ’¡ Feature Request
    url: https://github.com/jesec/flood/discussions/new
    about: Share ideas for new features
  - name: â“ Question
    url: https://github.com/jesec/flood/discussions/new
    about: General questions
  - name: ğŸ™ï¸ Discussion
    url: https://github.com/jesec/flood/discussions/new
    about: Start a discussion here
  - name: ğŸ†˜ Support
    url: https://discord.gg/Z7yR5Uf
    about: Join Discord for real-time support
